# Generated by Django 5.2.14 on 2026-05-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_userpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
