# Generated by Django 5.2.14 on 2026-05-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_add_database_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chats_chatr_room_id_1025f0_idx',
            old_name='chats_chatr_room_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chats_chatr_user_id_1274cd_idx',
            old_name='chats_chatr_user_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chats_messa_room_id_0b525c_idx',
            old_name='chats_messag_room_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chats_messa_sender__411bbf_idx',
            old_name='chats_messag_sender_idx',
        ),
    ]
